### PR TITLE
[CAS] Fix Windows build for CAS unittest

### LINKED ISSUE #7883: CAS Unittests broken on Windows
```
FAILED: unittests/CAS/CMakeFiles/CASTests.dir/CASTestConfig.cpp.obj
C:\PROGRA~2\MICROS~2\2022\BUILDT~1\VC\Tools\MSVC\1437~1.328\bin\Hostx64\x64\cl.exe  /nologo /TP -DGTEST_HAS_RTTI=0 -DUNICODE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_GLIBCXX_ASSERTIONS -D_HAS_EXCEPTIONS=0 -D_LIBCPP_ENABLE_HARDENED_MODE -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -IS:\b\1\unittests\CAS -IS:\SourceCache\swift-project\llvm-project\llvm\unittests\CAS -IS:\b\1\include -IS:\SourceCache\swift-project\llvm-project\llvm\include -IS:\SourceCache\swift-project\llvm-project\third-party\unittest\googletest\include -IS:\SourceCache\swift-project\llvm-project\third-party\unittest\googlemock\include /GS- /Gw /Gy /Oi /Oy /Zc:inline /Zi /Zc:__cplusplus /Zc:inline /Zc:preprocessor /Zc:__cplusplus /Zi /Oi /bigobj /permissive- /W4 -wd4141 -wd4146 -wd4244 -wd4267 -wd4291 -wd4351 -wd4456 -wd4457 -wd4458 -wd4459 -wd4503 -wd4624 -wd4722 -wd4100 -wd4127 -wd4512 -wd4505 -wd4610 -wd4510 -wd4702 -wd4245 -wd4706 -wd4310 -wd4701 -wd4703 -wd4389 -wd4611 -wd4805 -wd4204 -wd4577 -wd4091 -wd4592 -wd4319 -wd4709 -wd5105 -wd4324 -w14062 -we4238 /Gw /O2 /Ob2  -std:c++17 -MD  /EHs-c- /GR- -UNDEBUG /showIncludes /Founittests\CAS\CMakeFiles\CASTests.dir\CASTestConfig.cpp.obj /Fdunittests\CAS\CMakeFiles\CASTests.dir\ /FS -c S:\SourceCache\swift-project\llvm-project\llvm\unittests\CAS\CASTestConfig.cpp
S:\SourceCache\swift-project\llvm-project\llvm\unittests\CAS\CASTestConfig.cpp(30): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
S:\SourceCache\swift-project\llvm-project\llvm\unittests\CAS\CASTestConfig.cpp(30): error C2065: 'constructor': undeclared identifier
S:\SourceCache\swift-project\llvm-project\llvm\unittests\CAS\CASTestConfig.cpp(30): error C2062: type 'void' unexpected                                                                                                                                                                 S:\SourceCache\swift-project\llvm-project\llvm\unittests\CAS\CASTestConfig.cpp(30): error C2143: syntax error: missing ';' before '{'                                                                                                                                                   S:\SourceCache\swift-project\llvm-project\llvm\unittests\CAS\CASTestConfig.cpp(30): error C2447: '{': missing function header (old-style formal list?)                                                                                                                                  [315/864] Building CXX object unittests\CAS\CMakeFiles\CASTests.dir\ObjectStoreTest.cpp.obj                                                                                                                                                                                             S:\SourceCache\swift-project\llvm-project\third-party\unittest\googletest\include\gtest/internal/custom/raw-ostream.h(68): warning C4180: qualifier applied to function type has no meaning; ignored                                                                                    S:\SourceCache\swift-project\llvm-project\third-party\unittest\googletest\include\gtest/internal/custom/raw-ostream.h(34): note: see reference to class template instantiation 'llvm_gtest::StreamSwitch<T,void>' being compiled
        with
        [
            T=void (llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,uint64_t)
        ]
S:\SourceCache\swift-project\llvm-project\third-party\unittest\googletest\include\gtest/gtest-message.h(132): note: see reference to function template instantiation 'decltype(auto) llvm_gtest::printable<T>(T (__cdecl &))' being compiled
        with
        [
            T=void (llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,uint64_t)
        ]
S:\SourceCache\swift-project\llvm-project\third-party\unittest\googletest\include\gtest/gtest.h(2223): note: see reference to function template instantiation 'testing::Message &testing::Message::operator <<<T>(T (__cdecl &))' being compiled
        with
        [
            T=void (llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,uint64_t)
        ]
S:\SourceCache\swift-project\llvm-project\llvm\unittests\CAS\ObjectStoreTest.cpp(286): note: see reference to function template instantiation 'testing::ScopedTrace::ScopedTrace<void(llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,uint64_t)>(const char *,int,T (__cdecl &))' being compiled
        with
        [
            T=void (llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,uint64_t)
        ]
S:\SourceCache\swift-project\llvm-project\third-party\unittest\googletest\include\gtest/internal/custom/raw-ostream.h(53): warning C4180: qualifier applied to function type has no meaning; ignored
S:\SourceCache\swift-project\llvm-project\third-party\unittest\googletest\include\gtest/internal/custom/raw-ostream.h(36): note: see reference to class template instantiation 'llvm_gtest::RawStreamProxy<T>' being compiled
        with
        [
            T=void (llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,llvm::cas::ObjectStore &,uint64_t)
        ]
[323/864] Building CXX object unittests\CodeGen\CMakeFiles\CodeGenTests.dir\AArch64SelectionDAGTest.cpp.obj
```

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Fix the CAS unit-test build for windows which doesn't have the same setenv function and constructor attributes. Implement the default ondisk cas differently so it can be overwritten from environmental variable, using command-line opts or overwrite the value in process directly.

Fix: https://github.com/apple/llvm-project/issues/7883

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
@swift-ci please test llvm

**Review by compnerd — APPROVED** [review]
Thank you!

File: llvm/lib/CAS/OnDiskCommon.cpp [hunk 1]
```diff
@@ -8,19 +8,41 @@
...
 #include "llvm/ADT/StringRef.h"
+#include "llvm/Support/CommandLine.h"
 #include "llvm/Support/Error.h"
+#include "llvm/Support/Process.h"
+#include <mutex>
+#include <optional>
 
 using namespace llvm;
 
+cl::opt<uint64_t> OnDiskCASMaxMappingSize(
```
Comment (benlangmuir) [inline llvm/lib/CAS/OnDiskCommon.cpp]: Can we use `ManagedStatic` or otherwise avoid the global constructor for this option?

Comment (cachemeifyoucan) [reply llvm/lib/CAS/OnDiskCommon.cpp]: Fixed. I guess we don't have a use case for `cl::opt`. Just use a static variable to store the overwritten value.

**Review by benlangmuir — APPROVED** [review]
thanks!
